apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  description: yes
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
status: {}
