apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'argocd'
    server: '*'
  sourceRepos:
  - '*'
