apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: git@github.com:resnostyle/k8s-gitops.git
    path: argoproj

    # helm specific config
    #    helm:
    #      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
    #      # Release name override (defaults to application name)
    #      releaseName: telegraf
    #
    #      version: v2
    #
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  # Sync policy
  syncPolicy: {}
