apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-movie-pv
  namespace: nfs
spec:
  storageClassName: media-movie
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.45
    path: "/mnt/user/Movies"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-movie-pvc
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-movie
  resources:
    requests:
      storage: 1Mi
