---
rook:
  hosts:
    kube-1:
      ansible_host: 192.168.2.212
    kube-2:
      ansible_host: 192.168.2.214
    kube-3:
      ansible_host: 192.168.2.213

bastion:
  hosts:
    bastion-1:
      ansible_host: 192.168.2.110
  vars:
    ansible_become: true
    haproxy_backend_servers:
      - name: app1
        address: 192.168.2.235:5000
k3s_cluster:
  hosts:
    kube-0:
      ansible_host: 192.168.2.173
    kube-1:
      ansible_host: 192.168.2.192
    kube-2:
      ansible_host: 192.168.2.191
    kube-3:
      ansible_host: 192.168.2.194
    kube-4:
      ansible_host: 192.168.2.116
    kube-5:
      ansible_host: 192.168.2.221
  vars:
    ansible_user: bryan
    ansible_python_interpreter: /usr/bin/python3
    k3s_state: uninstalled
