---
- name: k3s_cluster
  hosts: k3s_cluster
  vars:
    k3s_become: true
    #    k3s_server: "{{ lookup('file', 'server_config/k3s_server.yml') | from_yaml }}"
    #    k3s_agent: "{{ lookup('file', 'server_config/k3s_agent.yml') | from_yaml }}"
  roles:
    - role: xanmanning.k3s
