---
#- name: k3s_cluster
#  hosts: k3s_cluster
#  vars:
#    k3s_become: true
#    k3s_server:
#      disable:
#        - traefik
#    #    k3s_server: "{{ lookup('file', 'server_config/k3s_server.yml') | from_yaml }}"
#    #    k3s_agent: "{{ lookup('file', 'server_config/k3s_agent.yml') | from_yaml }}"
#  roles:
#    - role: xanmanning.k3s
#    - role: local.packages
#

- name: bastion
  hosts: bastion
  vars:
    haproxy_frontend_name: 'hafrontend'
    haproxy_frontend_bind_address: '*'
    haproxy_frontend_port: 80
    haproxy_frontend_mode: 'tcp'
    certbot_auto_renew: true
    certbot_auto_renew_hour: "1"
    certbot_auto_renew_minute: "55"
    certbot_repo: "https://github.com/certbot/certbot.git"
    certbot_version: master
    certbot_install_method: source
    certbot_dir: "/opt/certbot"
    certbot_keep_updated: true
    certbot_certs:
      certbot_admin_email: bwp.pearson@gmail.com
      domains:
        - bryanwp.com
  roles:
    - role: ansible-host-setup
    - role: local.haproxy
    - role: geerlingguy.git
