---
collections:
#  - name: community.docker
#    version: 2.0.2
  - name: ansible.posix
    version: 1.3.0
  - name: kubernetes.core
    version: 2.2.2
  - name: community.sops
    version: 1.2.0
roles:
  - src: geerlingguy.pip
    version: 2.1.0
  - src: xanmanning.k3s
    version: v2.12.0
