apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/argo-cd-ui-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd
  newTag: 2.2.0-6d8ff61b
