apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-tv-pv
  namespace: arrs
spec:
  storageClassName: media-tv
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.45
    path: "/mnt/user/TV"
  mountOptions:
  - nfsvers=3
  - intr
  - hard
  - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-tv-pvc
  namespace: arrs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-tv
  resources:
    requests:
      storage: 1Mi
