apiVersion: v2
name: cluster-services
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
- name: ingress-nginx
  version: 4.0.18
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: metallb
  version: 0.12.1
  repository: "https://metallb.github.io/metallb"
- name: cert-manager
  version: v1.7.1
  repository: "https://charts.jetstack.io"
  #- name: traefik
  #  #  version:
  #  repository: "https://helm.traefik.io/traefik"
  #  #- name: rook-ceph
  #  version: v1.8.0
  #  repository: "https://charts.rook.io/release"
